import pygame

# Tapestry
GENERIC = -1 # No specific type
PALLETE = 0
PALLETE_SELECTOR = 1
COLOR_PICKER = 2
LAYER_MANAGER = 3
FRAME_MANAGER = 4
TOOLS = 5

MENU = 9
SELECTION = 10

#Buttons
ICON = 100
TEXT = 101

BUTTON = 102
TOOLBT = 103
LAYERBT = 104
KNOB = 105
FRAMEBT = 106
ROLLBT = 107
POPUPBT = 108
SELECTBT = 109
SLIDERBT = 110
TEXTBT = 111
TOGGLEBT = 112

#_____Separate_Numbering_____#
#Template
COMPONENT = 0
SLIDE_PANEL = 1
TEMPLATE = 2

#_____EVENTS_____#
BUILD = pygame.USEREVENT + 2
BUILD_EV = pygame.event.Event(BUILD)

LOAD = pygame.USEREVENT + 3
LOAD_EV = pygame.event.Event(LOAD)